install:
  - choco install gitversion.portable -pre -y

assembly_info:
  patch: false

before_build:
  - nuget restore Sources\UnlocLoader.sln
  - ps: gitversion /l console /output buildserver /updateAssemblyInfo

build:
  project: Sources\UnlocLoader.sln

after_build:
  - cmd: ECHO nuget pack Sources\UnlocLoader\UnlocLoader.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: nuget pack Sources\UnlocLoader\UnlocLoader.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%"
  - cmd: appveyor PushArtifact "CSharp-Unloc-Loader.%GitVersion_NuGetVersion%.nupkg"